/* Generated by https://github.com/janjongboom/mbed-js-wrapper-generator */

#ifndef _JERRYSCRIPT_MBED_HTTPRESPONSE_H
#define _JERRYSCRIPT_MBED_HTTPRESPONSE_H

#include "jerryscript-mbed-library-registry/wrap_tools.h"
#include "http_response.h"

DECLARE_CLASS_CONSTRUCTOR(HttpResponse);
jerry_value_t mbed_js_wrap_native_object(HttpResponse* ptr);

#endif // _JERRYSCRIPT_MBED_HTTPRESPONSE_H
