/* Generated by https://github.com/janjongboom/mbed-js-wrapper-generator */

#ifndef _JERRYSCRIPT_MBED_HTTPREQUEST_H
#define _JERRYSCRIPT_MBED_HTTPREQUEST_H

#include "jerryscript-mbed-library-registry/wrap_tools.h"
#include "http_request.h"

DECLARE_CLASS_CONSTRUCTOR(HttpRequest);
static jerry_value_t mbed_js_wrap_native_object(HttpRequest* ptr);

#endif // _JERRYSCRIPT_MBED_HTTPREQUEST_H
