/* Generated by https://github.com/janjongboom/mbed-js-wrapper-generator */

#ifndef _JERRYSCRIPT_MBED_LIB_HTTPRESPONSE_H
#define _JERRYSCRIPT_MBED_LIB_HTTPRESPONSE_H

#include "http_response.h"

#include "mbed-js-httpresponse/mbed-js-httpresponse.h"
#include "mbed-js-httprequest/mbed-js-httprequest.h"
#include "jerryscript-mbed-library-registry/wrap_tools.h"

void mbed_js_httpresponse_setup();
void mbed_js_httprequest_setup();

DECLARE_JS_WRAPPER_REGISTRATION (mbed_js_http)
{
    REGISTER_CLASS_CONSTRUCTOR(HttpResponse);
    mbed_js_httpresponse_setup();

    REGISTER_CLASS_CONSTRUCTOR(HttpRequest);
    mbed_js_httprequest_setup();
}

#endif // _JERRYSCRIPT_MBED_LIB_HTTPRESPONSE_H
